export const config = {
	baseURL: <string>process.env.CONCERO_API_URL,
	headers: { 'Content-Type': 'application/json' },
	CRYPTOPANIC_API_KEY: <string>process.env.CRYPTOPANIC_API_KEY,
	LIFI_INTEGRATOR: <string>process.env.LIFI_INTEGRATOR,
	LIFI_FEES: <string>process.env.LIFI_FEES,
	RANGO_API_KEY: <string>process.env.RANGO_API_KEY,
	ENSO_API_KEY: <string>process.env.ENSO_API_KEY,
	POSTHOG_API_KEY: <string>process.env.POSTHOG_API_KEY,
	POSTHOG_HOST: <string>process.env.POSTHOG_HOST,
	NULL_ADDRESS: '0x0000000000000000000000000000000000000000',
	NULL_E_ADDRESS: '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
	WEB3_MODAL_PROJECT_ID: process.env.WEB3_MODAL_PROJECT_ID,
	REFERRAL_PROGRAM_ADDRESS: <string>process.env.REFERRAL_PROGRAM_ADDRESS,
}
