export const routes = {
	home: '/',
	root: '/',
	swap: '/swap',
	auth: '/auth',
	login: '/login',
	signup: '/signup',
	profile: '/profile',
	earn: '/earn',
	portfolio: '/portfolio',
	referral: '/referral',
	join: '/join',
	notFound: '/404',
	resetPassword: '/reset-password',
}
